# Generated by Django 3.2 on 2022-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220323_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Terrace', 'Terrace'), ('Duplex', 'Duplex'), ('Apartments', 'Apartments'), ('Land', 'Land'), ('Hotels', 'Hotels'), ('Estate Market', 'Estate Market')], max_length=250),
        ),
    ]
