# Generated by Django 3.2 on 2022-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20220324_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
